### ISSUE TITLE
Inconsistent syntax highlighting on apache-multisite docs

### ISSUE THREAD

**Issue by msmit5** [rocky-linux/documentation#1355]
Markdown syntax highlighting for apache config blocks is inconsistently applied on the apache-multisite pages. This inconsistency also applies to translations, and considering this is more of a markdown inconsistency rather than a wording error, I plan on fixing it in the translations even if I do not speak the language.

On the following pages, there are apache configs without syntax highlighting
  - https://docs.rockylinux.org/guides/web/apache-sites-enabled/
  - https://docs.rockylinux.org/fr/guides/web/apache-sites-enabled/
  - https://docs.rockylinux.org/it/guides/web/apache-sites-enabled/
  - https://docs.rockylinux.org/zh/guides/web/apache-sites-enabled/

Example of a block with no highlighting: 
<img width="787" alt="image" src="https://github.com/rocky-linux/documentation/assets/55892653/077525c3-a110-414b-9651-ec4131b219b7">

Example of a block with syntax highlighting
<img width="770" alt="image" src="https://github.com/rocky-linux/documentation/assets/55892653/00a4bbe8-888c-41bb-b6d2-ee65b028edd2">

**Comment by sspencerwire** [comment]
Hey @msmit5 Thank you!  Please just make these changes to the source (English) document, rather than to the translated files too. Our translation interface will pick up the change and then the translators will approve or fix in the interface as necessary. Making direct changes to the translated files causes issues within Crowdin that become problematic.
