### ISSUE TITLE
migrate2rocky: advise on path for CENTOS 7

### ISSUE THREAD

**Issue by fulldecent** [rocky-linux/documentation#716]
In some sense version 7 is the "last version" of CENTOS.

The guide at https://docs.rockylinux.org/guides/migrate2rocky/ could please include a note about upgrading from CENTOS 7. Maybe this is just a link to Red Hat's documentation on this topic. But either way I stopped trusting Red Hat since CENTOS 7 was released, so hearing from you would be reassuring.

**Comment by hbjydev** [comment]
I'm not sure there _is_ really a way to do this with CentOS 8 being gone... Previously (i.e. before January 2022), you could have used Leapp to upgrade CentOS 7 -> CentOS 8 and then use migrate2rocky to switch from CentOS 8 to Rocky Linux 8. Not so sure how this would work now.

**Comment by fulldecent** [comment]
Thank you. I found a few detailed guides out there about this. Here is one https://www.golinuxcloud.com/migrate-centos-to-rocky-linux/#Step-1_Upgrade_CentOS_7_to_CentOS_8

But in general I'm looking for something to be blessed by this project.

**Comment by sspencerwire** [comment]
@fulldecent Did you get this figured out? As with @hbjydev I'm not sure it is possible to do anymore with Centos 8 gone. However, I'm willing to give this a try via a container using the link you provided. Best way to do that is to have the packages installed that you are using so that it can be fully tested (apache, mariadb, etc.) on a CentOS 7 instance. It won't be exactly like doing this on a bare metal machine, but I can give you a possible result at least. Let me know if you'd like me to try this. It's easy enough to do.

**Comment by sspencerwire** [comment]
Closing this issue. Thanks @fulldecent and @hbjydev
