### ISSUE TITLE
Import Rocky Linux to WSL

### ISSUE THREAD

**Issue by craph** [rocky-linux/documentation#859]
Hello,
In the official documentation to Import Rocky Linux to WSL please could you clarify how and where to find the container rootfs ?

We have this : 
Download the image from the [CDN images folder](https://dl.rockylinux.org/pub/rocky/9/images/) (if it is available)
Download the image from the latest [Github Action build](https://github.com/rocky-linux/sig-cloud-instance-images/actions/workflows/build.yml)
Extract the image from either Docker Hub or Quay.io ([ref.](https://docs.microsoft.com/en-us/windows/wsl/use-custom-distro#export-the-tar-from-a-container))

But in the CDN images folder the is no container rootfs I guess for windows user. In the Github Action build it looks the same I don't know what to use to import Rocky Linux to WSL.
And I don't have docker on my machine so I can't export the rootfs from a docker image.

Thank you very much for your help.

May be, is it plan to create an official WSL image that we can install from the Microsoft Store ?

**Comment by lumarel** [comment]
Hi @craph,

Sorry for the missing clarification, I was planning to improve that as soon as we really have those images available easily.
But as I want to add more stuff now anyway will do that in the next days!

Yes this is a current flaw of the builds, the  Rocky 9 images are still only accessable through Docker Hub and Quay.io

Soon (tm) there should be improvements as neil and me are working against a better release workflow for the docker / podman images. (I at least hope so)

The MS store was brought up a few times already, but hasn't progressed due to other tasks look [here](https://github.com/rocky-linux/WSL-DistroLauncher) for what has been done up to now.
If you want to help with that, best head over to Mattermost or IRC, help is very welcome 🙂

**Comment by lumarel** [comment]
@craph As 8.7 and 9.1 got released now, we also have the tarballs on the CDN!
Improved the documentation regarding that yesterday, should be very easy now to import Both Rocky 8 and 9 to WSL 🙂

**Comment by sspencerwire** [comment]
Since the documentation has been updated, I'm going to close this issue. Please feel free to open the issue again if there are still issues. Thanks @craph and @lumarel !
